#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.2 on Thu Apr 11 17:00:19 2019
#

import wx
import G

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((350, 180))
        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        self.textLambda = wx.TextCtrl(self.panel_3, wx.ID_ANY, "100", style=wx.TE_CENTRE)
        self.textp = wx.TextCtrl(self.panel_3, wx.ID_ANY, "0.001", style=wx.TE_CENTRE)
        self.ComfitmBtn = wx.Button(self.panel_3, wx.ID_ANY, "Comfirm")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.ComfirmEve, self.ComfitmBtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Automatic Whittaker Filter Baseline")
        self.ComfitmBtn.SetMinSize((100, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add((20, 5), 0, 0, 0)
        label_1 = wx.StaticText(self.panel_3, wx.ID_ANY, "Automatic Whittaker Filter Baseline")
        sizer_13.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
        sizer_13.Add((20, 10), 0, 0, 0)
        sizer_14.Add((20, 20), 1, wx.ALIGN_CENTER, 0)
        LambdaA = wx.StaticText(self.panel_3, wx.ID_ANY, u" λ")
        sizer_14.Add(LambdaA, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add(self.textLambda, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add((20, 10), 0, wx.ALIGN_CENTER, 0)
        pA = wx.StaticText(self.panel_3, wx.ID_ANY, "p")
        sizer_14.Add(pA, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add(self.textp, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add((20, 20), 1, 0, 0)
        sizer_13.Add(sizer_14, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        sizer_13.Add((20, 5), 0, 0, 0)
        sizer_15.Add((100, 20), 1, 0, 0)
        sizer_15.Add(self.ComfitmBtn, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 5)
        sizer_15.Add((100, 20), 1, 0, 0)
        sizer_13.Add(sizer_15, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_13)
        sizer_12.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_12)
        self.Layout()
        # end wxGlade

    def ConfirmEve(self, event):  # wxGlade: MyFrame.<event_handler>
        #print("Event handler 'ComfirmEve' not implemented!")
        #event.Skip()

        G.BaselineLambda = float(self.textLambda.GetValue())
        G.BaselineP = float(self.textp.GetValue())

        self.Destroy()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
