#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.2 on Thu Apr 11 17:07:04 2019
#

import wx
import G

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((350, 180))
        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        self.textwidth = wx.TextCtrl(self.panel_3, wx.ID_ANY, "5", style=wx.TE_CENTRE)
        self.textorder = wx.TextCtrl(self.panel_3, wx.ID_ANY, "0", style=wx.TE_CENTRE)
        self.ConfirmBtn = wx.Button(self.panel_3, wx.ID_ANY, "Confirm")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.ComfirmEve, self.ConfirmBtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("S-G Smoothing")
        self.ConfirmBtn.SetMinSize((100, 30))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add((20, 5), 0, 0, 0)
        label_1 = wx.StaticText(self.panel_3, wx.ID_ANY, "S-G Smoothing")
        sizer_13.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
        sizer_13.Add((20, 5), 0, 0, 0)
        sizer_14.Add((10, 20), 1, wx.ALIGN_CENTER, 0)
        widthA = wx.StaticText(self.panel_3, wx.ID_ANY, "width")
        sizer_14.Add(widthA, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add(self.textwidth, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add((5, 20), 0, wx.ALIGN_CENTER, 0)
        orderA = wx.StaticText(self.panel_3, wx.ID_ANY, "order")
        sizer_14.Add(orderA, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add(self.textorder, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add((10, 20), 1, 0, 0)
        sizer_13.Add(sizer_14, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        sizer_13.Add((20, 5), 0, 0, 0)
        sizer_15.Add((300, 5), 1, 0, 0)
        sizer_15.Add(self.ConfirmBtn, 0, wx.ALL, 5)
        sizer_15.Add((125, 5), 0, 0, 0)
        sizer_13.Add(sizer_15, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_13)
        sizer_12.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_12)
        self.Layout()
        # end wxGlade

    def ConfirmEve(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'ComfirmEve' not implemented!")
        event.Skip()

        G.SWidth = float(self.textwidth.GetValue())
        G.SOrder = float(self.textorder.GetValue())

        self.Destroy()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
