#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.2 on Thu Apr 11 16:36:17 2019
#

import wx
import G

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((500, 200))
        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        self.LeftEnd = wx.TextCtrl(self.panel_3, wx.ID_ANY, "1800", style=wx.TE_CENTRE)
        self.RightEnd = wx.TextCtrl(self.panel_3, wx.ID_ANY, "800", style=wx.TE_CENTRE)
        self.ConfirmBtn = wx.Button(self.panel_3, wx.ID_ANY, "Confirm")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.getValues, self.ConfirmBtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Feature Band Select")
        self.SetSize((500, 200))
        self.ConfirmBtn.SetMinSize((100, 30))
        self.panel_3.SetMinSize((500, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add((20, 10), 0, 0, 0)
        label_1 = wx.StaticText(self.panel_3, wx.ID_ANY, "Characteristic Band")
        sizer_13.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
        sizer_13.Add((20, 5), 0, 0, 0)
        sizer_14.Add((20, 20), 1, wx.ALIGN_CENTER, 0)
        label_2 = wx.StaticText(self.panel_3, wx.ID_ANY, "Left End")
        sizer_14.Add(label_2, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add(self.LeftEnd, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        label_3 = wx.StaticText(self.panel_3, wx.ID_ANY, "cm-1")
        sizer_14.Add(label_3, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add((20, 20), 0, wx.ALIGN_CENTER, 0)
        label_4 = wx.StaticText(self.panel_3, wx.ID_ANY, "Right End")
        sizer_14.Add(label_4, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add(self.RightEnd, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        label_5 = wx.StaticText(self.panel_3, wx.ID_ANY, "cm-1")
        sizer_14.Add(label_5, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_14.Add((20, 20), 1, 0, 0)
        sizer_13.Add(sizer_14, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        sizer_13.Add((20, 5), 0, 0, 0)
        sizer_15.Add((200, 20), 1, 0, 0)
        sizer_15.Add(self.ConfirmBtn, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_15.Add((200, 20), 1, 0, 0)
        sizer_13.Add(sizer_15, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_13)
        sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def getValues(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'getValues' not implemented!")
        event.Skip()
        G.spEndL = float(self.LeftEnd.GetValue())
        print(G.spEndL)
        G.spEndR = float(self.RightEnd.GetValue())
        print(G.spEndR)
        self.Destroy()

# end of class MyDialog

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # Content of this block not found. Did you rename this class?
        pass

    def __set_properties(self):
        # Content of this block not found. Did you rename this class?
        pass

    def __do_layout(self):
        # Content of this block not found. Did you rename this class?
        pass

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
